name: CI Lint And Test

on:
  push:
    branches: [ main ]
  pull_request:

env:
  GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
  TARBALL_PATH: test/e2e/node-anvil.tgz

jobs:

  # Several things need this, so we do it up front once for caching/performance
  prepare-node:
    name: Prepare Node
    runs-on: ubuntu-latest
    outputs:
      build-node-version: ${{ steps.setup-node.outputs.node-version }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'
    - run: yarn install

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: prepare-node

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'

    - run: yarn install
    - run: yarn lint:quiet

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    needs:
      - prepare-node

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'
    - run: yarn install
    - run: yarn test

  build-e2e-package:
    name: Build E2E Package
    runs-on: ubuntu-latest
    needs: prepare-node

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'

    - name: Cache Package Build
      uses: actions/cache@v3
      with:
        # We'll cache this file
        path: ${{ env.TARBALL_PATH }}
        key: ${{ runner.os }}-node-${{ needs.prepare-node.outputs.build-node-version }}-${{ env.GITHUB_SHA }}

    - run: yarn install
    - run: yarn test-e2e:build

  supported-version-sanity-checks:
    name: Sanity Checks
    runs-on: ubuntu-latest
    needs:
      - prepare-node
      - build-e2e-package
    strategy:
      matrix:
        node-version: [12, 14, 16, 18]
        include:
          - node-version: 14
            npm-version: 7
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Restore Cached Package Build
      uses: actions/cache@v3
      with:
        # This is the file to cache / restore
        path: ${{ env.TARBALL_PATH }}
        key: ${{ runner.os }}-node-${{ needs.prepare-node.outputs.build-node-version }}-${{ env.GITHUB_SHA }}

    # Some versions of Node (like Node 14) ships with a version of NPM that does not work for us
    # so we need to install a specific version
    - name: Optionally update NPM if needed
      if: ${{ matrix.npm-version }}
      run: npm i -g npm@${{ matrix.npm-version }}
    # Just make sure it installs correctly for now and we'll call it good. No testing.
    - run: yarn test-e2e:install

